import { useEffect, useMemo, useState } from "react";
import { api, type Opportunity, type Template, type TemplateSection } from "../api";

const VAR_RE = /\{\{\s*([a-zA-Z_][\w\.]*)\s*\}\}/g;

function money(v: number) {
  return "R " + v.toLocaleString("en-ZA", { maximumFractionDigits: 2 });
}

function buildContext(tpl: Template, opp: Opportunity | null) {
  if (opp) {
    const subtotal = opp.lines.reduce((s, l) => s + l.line_total, 0);
    const totalArea = opp.lines
      .filter((l) => l.unit_of_measure === "m²")
      .reduce((s, l) => s + l.quantity, 0);
    return {
      client: {
        name: opp.client.name,
        industry: opp.client.industry,
        contact_person: opp.client.contact_person,
        email: opp.client.email,
        phone: opp.client.phone,
        site_location: opp.client.site_location,
      },
      opportunity: {
        title: opp.title,
        delivery_weeks: String(opp.delivery_weeks),
        priority: String(opp.priority),
        notes: opp.notes,
      },
      ref: "AMBS-PREVIEW-0001",
      date: new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" }),
      amount: money(subtotal),
      subtotal: money(subtotal),
      total_area_m2: totalArea.toLocaleString("en-ZA", { maximumFractionDigits: 0 }),
      n_items: String(opp.lines.length),
    };
  }
  return {
    client: {
      name: "Sample Client (Pty) Ltd",
      industry: "Mining",
      contact_person: "Sample Contact",
      email: "contact@sample.co.za",
      phone: "+27 00 000 0000",
      site_location: "Johannesburg, Gauteng",
    },
    opportunity: {
      title: "Sample Opportunity",
      delivery_weeks: "6",
      priority: "3",
      notes: "Sample notes.",
    },
    ref: "AMBS-PREVIEW-0001",
    date: new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" }),
    amount: "R 1,000,000",
    subtotal: "R 1,000,000",
    total_area_m2: "0",
    n_items: "0",
  };
}

function subst(text: string, ctx: any): string {
  if (!text) return "";
  return text.replace(VAR_RE, (_m, path) => {
    const parts = path.split(".");
    let cur: any = ctx;
    for (const p of parts) {
      if (cur && typeof cur === "object" && p in cur) cur = cur[p];
      else return `{{${path}}}`;
    }
    return String(cur);
  });
}

export default function TemplatePreview({
  template,
  onClose,
}: {
  template: Template;
  onClose: () => void;
}) {
  const [opps, setOpps] = useState<Opportunity[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);

  useEffect(() => {
    api.opportunities.list().then((list) => {
      setOpps(list);
      if (list.length) setSelectedId(list[0].id);
    });
  }, []);

  const opp = useMemo(
    () => opps.find((o) => o.id === selectedId) ?? null,
    [opps, selectedId]
  );
  const ctx = useMemo(() => buildContext(template, opp), [template, opp]);

  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex" onClick={onClose}>
      <div
        className="ml-auto bg-slate-200 w-full md:w-[900px] h-full shadow-2xl flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="px-4 py-2 bg-white border-b border-ui-border flex items-center gap-3">
          <div className="text-[13px] font-display font-bold text-sai-navy">Preview</div>
          <div className="text-slate-300">·</div>
          <div className="text-[12px] text-slate-500 truncate">{template.name}</div>
          <div className="flex-1" />
          <label className="text-[11px] text-slate-500">Using data from</label>
          <select
            value={selectedId ?? ""}
            onChange={(e) => setSelectedId(e.target.value ? Number(e.target.value) : null)}
            className="text-[11px] border border-ui-border rounded px-2 py-1 outline-none focus:border-sai-blue bg-white max-w-[280px]"
          >
            <option value="">— sample data —</option>
            {opps.map((o) => (
              <option key={o.id} value={o.id}>
                {o.title} · {o.client.name}
              </option>
            ))}
          </select>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 text-[16px] leading-none px-2"
            title="Close preview"
          >
            ×
          </button>
        </div>

        <div className="flex-1 overflow-y-auto scroll-thin p-6">
          <PaperSheet>
            {template.sections
              .filter((s) => s.enabled)
              .map((s, i) => (
                <Section key={i} section={s} template={template} ctx={ctx} opp={opp} />
              ))}
            <div className="mt-8 pt-3 border-t border-slate-200 text-[9px] text-slate-400">
              Generated by SolutionsAI Proposal Generator · Template: {template.name} · {ctx.date}
            </div>
          </PaperSheet>
        </div>
      </div>
    </div>
  );
}

function PaperSheet({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="bg-white shadow-xl mx-auto px-12 py-10"
      style={{ maxWidth: 760, minHeight: 1070, fontFamily: "Calibri, 'Open Sans', sans-serif" }}
    >
      {children}
    </div>
  );
}

function Section({
  section,
  template,
  ctx,
  opp,
}: {
  section: TemplateSection;
  template: Template;
  ctx: any;
  opp: Opportunity | null;
}) {
  const primary = template.brand_primary_color || "#2563B0";
  const accent = template.brand_accent_color || "#0B1120";
  const cfg = section.config || {};

  switch (section.kind) {
    case "header": {
      const logoUrl = template.logo_filename ? api.templates.logoUrl(template.logo_filename) : "";
      return (
        <div className="mb-5">
          {logoUrl && <img src={logoUrl} alt="Logo" className="h-14 mb-2 object-contain" />}
          <div className="flex items-end gap-3">
            <div className="text-[22pt] font-bold" style={{ color: accent }}>
              {template.brand_company_name || "AMBS"}
            </div>
            {template.brand_tagline && (
              <div className="text-[11pt] text-slate-500 pb-1">{template.brand_tagline}</div>
            )}
          </div>
          {template.brand_address_line && <div className="text-[9pt] text-slate-500 mt-1">{template.brand_address_line}</div>}
          {template.brand_contact_line && <div className="text-[9pt] text-slate-500">{template.brand_contact_line}</div>}
          <div className="mt-5 text-[18pt] font-bold" style={{ color: primary }}>
            {subst(cfg.title ?? "PROJECT PROPOSAL", ctx)}
          </div>
          {cfg.show_reference !== false && (
            <div className="text-[9pt] text-slate-500 mt-0.5">
              Reference: {ctx.ref}   ·   Issued: {ctx.date}
            </div>
          )}
        </div>
      );
    }
    case "client_info":
      return (
        <div className="mb-5">
          <Heading text={cfg.heading || "Prepared For"} color={accent} />
          <KvTable
            rows={[
              ["Client", ctx.client.name || "—"],
              ["Industry", ctx.client.industry || "—"],
              ["Contact", ctx.client.contact_person || "—"],
              ["Email", ctx.client.email || "—"],
              ["Phone", ctx.client.phone || "—"],
              ["Site Location", ctx.client.site_location || "—"],
            ]}
            accent={accent}
          />
        </div>
      );
    case "text":
      return (
        <div className="mb-5">
          {cfg.heading && <Heading text={subst(cfg.heading, ctx)} color={accent} />}
          <div className="text-[10pt] whitespace-pre-wrap leading-snug">
            {subst(cfg.body ?? "", ctx)}
          </div>
        </div>
      );
    case "scope": {
      const autoBullets: string[] = [];
      if (cfg.auto_include_lines !== false && opp) {
        const byPL: Record<string, { desc: string; qty: number; uom: string }[]> = {};
        for (const ln of opp.lines) {
          if (!ln.product_line) continue;
          (byPL[ln.product_line] ??= []).push({ desc: ln.description, qty: ln.quantity, uom: ln.unit_of_measure });
        }
        for (const pl of Object.keys(byPL)) {
          autoBullets.push(`**${pl}**`);
          for (const d of byPL[pl]) {
            if (!d.desc) continue;
            autoBullets.push(`  ${d.desc} (${d.qty} ${d.uom})`);
          }
        }
      }
      const items: string[] = cfg.items ?? [];
      return (
        <div className="mb-5">
          <Heading text={cfg.heading || "Scope of Work"} color={accent} />
          <ul className="list-disc pl-5 text-[10pt] space-y-0.5">
            {autoBullets.map((b, i) => {
              const bold = b.startsWith("**");
              const txt = bold ? b.replace(/\*\*/g, "") : b;
              return (
                <li key={`auto-${i}`} className={bold ? "font-semibold" : ""}>
                  {txt}
                </li>
              );
            })}
            {items.map((s, i) => (
              <li key={`item-${i}`}>{subst(s, ctx)}</li>
            ))}
          </ul>
        </div>
      );
    }
    case "line_items": {
      if (!opp) {
        return (
          <div className="mb-5">
            <Heading text={cfg.heading || "Line Items"} color={accent} />
            <div className="text-[9pt] text-slate-400 italic">Pick an opportunity above to preview line items.</div>
          </div>
        );
      }
      const subtotal = opp.lines.reduce((s, l) => s + l.line_total, 0);
      return (
        <div className="mb-5">
          <Heading text={cfg.heading || "Line Items"} color={accent} />
          <table className="w-full text-[9pt] border-collapse">
            <thead>
              <tr style={{ color: accent }} className="font-bold border-b-2" >
                <th className="text-left p-1">#</th>
                <th className="text-left p-1">Description</th>
                <th className="text-left p-1">Category</th>
                <th className="text-right p-1">Qty</th>
                <th className="text-left p-1">UoM</th>
                <th className="text-right p-1">Unit Rate</th>
                <th className="text-right p-1">Line Total</th>
              </tr>
            </thead>
            <tbody>
              {opp.lines.map((ln, i) => (
                <tr key={ln.id} className="border-b border-slate-200 align-top">
                  <td className="p-1 text-slate-500">{i + 1}</td>
                  <td className="p-1">
                    {ln.product_line && <div className="font-semibold">{ln.product_line}</div>}
                    {ln.description && <div className="text-slate-600">{ln.description}</div>}
                  </td>
                  <td className="p-1 text-slate-600">{ln.structure_type || ln.product_line || "—"}</td>
                  <td className="p-1 text-right tabular-nums">{ln.quantity}</td>
                  <td className="p-1">{ln.unit_of_measure}</td>
                  <td className="p-1 text-right tabular-nums">{money(ln.unit_rate)}</td>
                  <td className="p-1 text-right tabular-nums">{money(ln.line_total)}</td>
                </tr>
              ))}
              <tr className="font-bold" style={{ color: accent }}>
                <td colSpan={6} className="p-1 text-right">Subtotal (excl. VAT)</td>
                <td className="p-1 text-right tabular-nums">{money(subtotal)}</td>
              </tr>
            </tbody>
          </table>
        </div>
      );
    }
    case "commercial": {
      const subtotal = opp ? opp.lines.reduce((s, l) => s + l.line_total, 0) : 0;
      const vatPct = Number(cfg.vat_percent ?? 15);
      const vat = (subtotal * vatPct) / 100;
      const totalArea = opp
        ? opp.lines.filter((l) => l.unit_of_measure === "m²").reduce((s, l) => s + l.quantity, 0)
        : 0;
      const rows: [string, string][] = [
        ["Line items", String(opp?.lines.length ?? 0)],
      ];
      if (totalArea) rows.push(["Total area (m²)", `${totalArea.toLocaleString("en-ZA")} m²`]);
      rows.push(
        ["Subtotal (ex VAT)", money(subtotal)],
        [`VAT (${vatPct}%)`, money(vat)],
        ["Total (incl VAT)", money(subtotal + vat)],
        ["Payment terms", subst(cfg.payment_terms ?? "", ctx)],
        ["Delivery", `${opp?.delivery_weeks ?? "—"} weeks from signed order & cleared deposit`],
        ["Validity", `${cfg.validity_days ?? 30} days from issue date`],
      );
      return (
        <div className="mb-5">
          <Heading text={cfg.heading || "Commercial Summary"} color={accent} />
          <KvTable rows={rows} accent={accent} />
        </div>
      );
    }
    case "why_us": {
      const bullets: string[] = cfg.bullets ?? [];
      return (
        <div className="mb-5">
          <Heading text={cfg.heading || "Why Us"} color={accent} />
          <ul className="list-disc pl-5 text-[10pt] space-y-0.5">
            {bullets.map((b, i) => (
              <li key={i}>{subst(b, ctx)}</li>
            ))}
          </ul>
        </div>
      );
    }
    case "signature":
      return (
        <div className="mb-5">
          <Heading text={cfg.heading || "Acceptance"} color={accent} />
          <div className="text-[10pt] leading-snug">{subst(cfg.preface ?? "", ctx)}</div>
          <div className="mt-4 text-[10pt]">
            {cfg.client_label || "Signed for the Client"}: ____________________________   Date: ____________
          </div>
          <div className="mt-3 text-[10pt]">
            {cfg.company_label || "Signed for Company"}: _______________________________   Date: ____________
          </div>
        </div>
      );
    case "page_break":
      return (
        <div className="my-8 border-t border-dashed border-slate-300 relative">
          <div className="absolute -top-2 left-1/2 -translate-x-1/2 bg-white text-[9px] uppercase tracking-wider text-slate-400 px-2">
            Page break
          </div>
        </div>
      );
    default:
      return <div className="text-[9pt] text-slate-400 italic mb-3">Unknown section: {section.kind}</div>;
  }
}

function Heading({ text, color }: { text: string; color: string }) {
  return (
    <div className="text-[12pt] font-bold mb-1.5" style={{ color }}>
      {text}
    </div>
  );
}

function KvTable({ rows, accent }: { rows: [string, string][]; accent: string }) {
  return (
    <table className="w-full text-[10pt]">
      <tbody>
        {rows.map(([k, v], i) => (
          <tr key={i} className="align-top">
            <td className="py-0.5 pr-3 font-semibold w-[33%]" style={{ color: accent }}>{k}</td>
            <td className="py-0.5">{v}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
